### ISSUE TITLE
Create data model

### ISSUE THREAD

**Issue by maximiliani** [maximiliani/idoris#2]
Based on schemas developed in [FDConcepts](https://github.com/maximiliani/FDConcepts) repository
- [ ] FD Objects
- [ ] FD Data Types
- [ ] FD Type Profiles
- [ ] FD Operations
- [ ] FD Operation Type Profiles

Additional data types:
- [ ] Users
 - [ ] ORCiD
 - [ ] manual registration (first name, last name, mail address?)

**Comment by nicolasblumenroehr** [comment]
- UML class diagram for the model
